from dotenv import load_dotenv
import os
load_dotenv()

API_BASE_NAME= os.getenv("API_BASE_NAME")
API_VERSION= os.getenv("API_VERSION")
DATABASE_USER= os.getenv("DATABASE_USER")
DATABASE_PASSWORD= os.getenv("DATABASE_PASSWORD")
DATABASE_HOST= os.getenv("DATABASE_HOST")
DATABASE_NAME= os.getenv("DATABASE_NAME")
DATABASE_SSL_MODE= os.getenv("DATABASE_SSL_MODE")
JWT_SECRET_KEY= os.getenv("JWT_SECRET_KEY")
JWT_ALGORITHM= os.getenv("JWT_ALGORITHM")
JWT_TOKEN_TIME_HOURS= os.getenv("JWT_TOKEN_TIME_HOURS")
LLM_MODEL= os.getenv("LLM_MODEL")
OPENAI_API_KEY= os.getenv("OPENAI_API_KEY")
CHUNK_SIZE= os.getenv("CHUNK_SIZE")
CHUNK_OVERLAP= os.getenv("CHUNK_OVERLAP")
EMBADDING_MODEL= os.getenv("EMBADDING_MODEL")

LAST_N_MESSAGES= os.getenv("LAST_N_MESSAGES")
NO_OF_ROW_SUMMARY= os.getenv("NO_OF_ROW_SUMMARY")

print(" Print config file values ====================================================================>")
print(f"API_BASE_NAME: {API_BASE_NAME}")
print(f"API_VERSION: {API_VERSION}")
print(f"DATABASE_USER: {DATABASE_USER}")
print(f"DATABASE_PASSWORD: {DATABASE_PASSWORD}")
print(f"DATABASE_HOST: {DATABASE_HOST}")
print(f"DATABASE_NAME: {DATABASE_NAME}")
print(f"DATABASE_SSL_MODE: {DATABASE_SSL_MODE}")
print(f"JWT_SECRET_KEY: {JWT_SECRET_KEY}")
print(f"JWT_ALGORITHM: {JWT_ALGORITHM}")
print(f"JWT_TOKEN_TIME_HOURS: {JWT_TOKEN_TIME_HOURS}")
print(f"LLM_MODEL: {LLM_MODEL}")
print(f"OPENAI_API_KEY: {OPENAI_API_KEY}")
print(f"CHUNK_SIZE: {CHUNK_SIZE}")
print(f"CHUNK_OVERLAP: {CHUNK_OVERLAP}")
print(f"EMBADDING_MODEL: {EMBADDING_MODEL}")
print(f"LAST_N_MESSAGES: {LAST_N_MESSAGES}")       
print(" Print config file values ====================================================================>")