from dotenv import load_dotenv
import os
load_dotenv()

API_BASE_NAME= os.getenv("API_BASE_NAME")
API_VERSION= os.getenv("API_VERSION")
DATABASE_USER= os.getenv("DATABASE_USER")
DATABASE_PASSWORD= os.getenv("DATABASE_PASSWORD")
DATABASE_HOST= os.getenv("DATABASE_HOST")
DATABASE_NAME= os.getenv("DATABASE_NAME")
DATABASE_SSL_MODE= os.getenv("DATABASE_SSL_MODE")
JWT_SECRET_KEY= os.getenv("JWT_SECRET_KEY")
JWT_ALGORITHM= os.getenv("JWT_ALGORITHM")
JWT_TOKEN_TIME_HOURS= os.getenv("JWT_TOKEN_TIME_HOURS")
LLM_MODEL= os.getenv("LLM_MODEL")
OPENAI_API_KEY= os.getenv("OPENAI_API_KEY")
CHUNK_SIZE= os.getenv("CHUNK_SIZE")
CHUNK_OVERLAP= os.getenv("CHUNK_OVERLAP")
EMBADDING_MODEL= os.getenv("EMBADDING_MODEL")

LAST_N_MESSAGES= os.getenv("LAST_N_MESSAGES")
NO_OF_ROW_SUMMARY= os.getenv("NO_OF_ROW_SUMMARY")