name: Deploy FastAPI

on:
  push:
    branches: [ main ]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker Image
      run: |
        docker build -t fastapi-app .

    - name: Tag Image
      run: |
        IMAGE_TAG=${{ github.run_number }}
        docker tag fastapi-app:IMAGE_TAG ${{ secrets.ECR_REPOSITORY }}:IMAGE_TAG

    - name: Push Image
      run: |
        IMAGE_TAG=${{ github.run_number }}
        docker push ${{ secrets.ECR_REPOSITORY }}:IMAGE_TAG

    - name: Deploy on EC2
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          IMAGE_TAG=${{ github.run_number }}
          docker pull ${{ secrets.ECR_REPOSITORY }}:IMAGE_TAG
          docker stop fastapi || true
          docker rm fastapi || true
          docker run -d -p 8000:8000 --name fastapi --restart unless-stopped ${{ secrets.ECR_REPOSITORY }}:IMAGE_TAG